### ISSUE TITLE
return this.model shouldn't be return getModel() ?

### ISSUE THREAD

**Issue by jolafrite** [mrnkr/nativescript-ngx-iphonex-safe-area#2]
https://github.com/mrnkr/nativescript-ngx-iphonex-safe-area/blob/996b0e261fd274ba06500f54673a3e4ac29d27f6/src/device-info.android.ts#L17

**Comment by mrnkr** [comment]
I am terribly sorry for the huge delay, never expected any feedback to be honest... You're right, this.model does not even exist 🤭 I'm fixing that right now
