### ISSUE TITLE
Readme Correction

### ISSUE THREAD

**Issue by jevenson** [mrnkr/nativescript-ngx-iphonex-safe-area#3]
The Readme states:
> Notice those blueish painted areas? Well, those are the safe area!

The blue areas in the diagram are actually the _unsafe_ areas, and the safe area is everything else.

**Comment by mrnkr** [comment]
First: I apologize for the loooong delay, never really expected to have any feedback... 😬 Second: You're right, I'll fix it right away, my bad!

**Comment by jevenson** [comment]
Ha, I forgot about this. Glad I could help.
